### ISSUE TITLE
tracking_hostname filter for destinations

### ISSUE THREAD

**Issue by clementgalopin** [jitsucom/eventnative#114]
Let's say you want to track events on several different websites, and for business or legal reasons, event logs need to be stored separately.

You most likely want to use one global eventnative infra with several instances and a load balancer for this.

It would then be great if you could set a tracking_hostname filter for each destination, so that only the right events are streamed to them.

**Comment by xtreding** [comment]
Hi @clementgalopin! Thank you for the issue and for using **EventNative!**
Now you can do it with different API keys. You could configure several API keys and set them to **only_tokens** field in the destination. Then you could use **EventNative** js pixel with `"key": client_secret` depends on what events would you like to have in what destinations. 


**EventNative** configuration example:
```
server:
    auth:
    -
      client_secret: 'token1'
    -
      client_secret: 'token2'
destinations:
    destination1:
        only_tokens:
            - token1
    destination2:
        only_tokens:
            - token2
```
More information about [API keys authorization](https://docs.eventnative.org/configuration-1/configuration/authorization#client-server-secrets-authorization)
More information about [destinations **only_tokens** configuration](https://docs.eventnative.org/configuration-1/configuration#yaml-configuration)

If you have any questions please let me know!
