### ISSUE TITLE
Support of singer-taps as a sources (singer bridge)

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/eventnative#139]
### Intro

[Singer](https://www.singer.io/) as an open-source framework for moving data from source (taps) to databases (targets). Though it's not very high performant, we can use it for part of connectors since API coverage is pretty impressive.

### Implementation

We should have a separate driver called singer that works as a bridge between Singer and EventNative. Here's a preliminary format of configuration:

```yaml
# Global config of singer bridge
signer-bridge:
  python: '/path/to/python' #optional, `which python3` by default
  venv_dir: #dir for python's venv, ./venv (relative to binary) by default

sources:
  test:
    type: singer
    destinations: "destination_id"
    collections: '*' # we need to support syntax for syncing all singer collections (they called streams there_
    config:
      singer:
        tap: tap-facebook
        config: {} #singer config (-c param)
        properties: {} # singer properties (-p parameter)
        initial_state: {} # initial state, ongoing state should be saved in Redis (-s parameter)
```

We should utilize [Python's venv](https://docs.python.org/3/library/venv.html) and install taps with pip on demand.
