### ISSUE TITLE
SQL logger improvement

### ISSUE THREAD

**Issue by akhtyamovrr** [jitsucom/eventnative#150]
### Problem

There is one configuration for all the SQL logs in one place and we write data to one file. It causes large files with much debug information. When there are large files or many rotation files, it takes more time to troubleshoot the problem. 

### Solution

Split DDL and other queries configuration to be able to turn on/off only required logs and to write data to different files.

Configuration example:
```yaml
sql_debug_log:
  ddl:
    path: '<logs_directory>'
    rotation_min: <rotation_period>
    max_backups: <backups_to_store>
  queries:
    path: '<logs_directory>'
    rotation_min: <rotation_period>
    max_backups: <backups_to_store>
```
